# Generated by Django 3.2.1 on 2021-05-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'waiting'), (2, 'processing'), (3, 'done'), (4, 'fail')], default=1, editable=False),
        ),
    ]
