# Generated by Django 3.2.1 on 2021-05-06 10:54

from django.db import migrations, models
import groups.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='000000', max_length=6, validators=[groups.validators.color])),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
